#!/usr/bin/env python3
import os
import feedparser
import resend
from datetime import datetime, timezone, timedelta

# 1. 自动从 GitHub Secrets 读取配置
resend.api_key = os.environ.get("RESEND_API_KEY")
receiver_email = os.environ.get("RECEIVER_EMAIL")

def read_feeds_file(filepath="feeds.txt"):
    """读取订阅源列表"""
    feeds = []
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    feeds.append(line)
    except FileNotFoundError:
        print(f"❌ 错误: 找不到 {filepath}")
        return []
    return feeds

def fetch_and_build_html(feeds):
    """抓取资讯并构建电子报纸样式的 HTML"""
    now = datetime.now(timezone.utc)
    
    # 报纸头部 CSS 样式
    html = """
    <div style="background-color: #f4f1ea; padding: 20px; font-family: 'Georgia', serif; color: #333;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border: 1px solid #d3d3d3; padding: 30px; box-shadow: 2px 2px 10px rgba(0,0,0,0.1);">
            <div style="text-align: center; border-bottom: 4px double #333; padding-bottom: 10px; margin-bottom: 20px;">
                <h1 style="margin: 0; font-size: 30px; text-transform: uppercase; letter-spacing: 2px;">Daily News Gazette</h1>
                <p style="margin: 5px 0; color: #666; font-style: italic;">{date}</p>
            </div>
    """.format(date=datetime.now().strftime('%A, %b %d, %Y'))

    total_entries = 0

    for url in feeds:
        try:
            print(f"正在抓取: {url}")
            feed = feedparser.parse(url)
            source_title = feed.feed.get('title', 'Global News')
            
            section_content = ""
            for entry in feed.entries:
                # 获取发布时间
                pub_parsed = getattr(entry, 'published_parsed', None) or getattr(entry, 'updated_parsed', None)
                if pub_parsed:
                    pub_date = datetime(*pub_parsed[:6], tzinfo=timezone.utc)
                    # --- 调试提示：如果想确保一定收到邮件，可以将 days=1 改为 days=30 ---
                    if (now - pub_date) < timedelta(days=1):
                        summary = entry.get('summary', '')[:120] + '...' if 'summary' in entry else ''
                        section_content += f"""
                        <div style="margin-bottom: 20px; padding-bottom: 15px; border-bottom: 1px solid #eee;">
                            <a href="{entry.link}" style="text-decoration: none; color: #c0392b; font-weight: bold; font-size: 17px; display: block; margin-bottom: 5px;">{entry.title}</a>
                            <p style="margin: 0; font-size: 14px; color: #555; line-height: 1.6;">{summary}</p>
                        </div>
                        """
                        total_entries += 1
            
            if section_content:
                html += f'<h2 style="font-size: 20px; border-left: 5px solid #333; padding-left: 10px; margin: 30px 0 15px 0; color: #1a1a1a; background: #f9f9f9;">{source_title}</h2>'
                html += section_content

        except Exception as e:
            print(f"解析错误 {url}: {e}")

    # 页脚
    html += """
            <div style="margin-top: 40px; border-top: 1px solid #333; padding-top: 15px; text-align: center; font-size: 12px; color: #888; font-style: italic;">
                <p>Generated by Rex's Newsletter Bot</p>
            </div>
        </div>
    </div>
    """
    return html if total_entries > 0 else None

def main():
    print("Newsletter Bot - 任务开始...")
    
    if not resend.api_key or not receiver_email:
        print("❌ 错误: GitHub Secrets 中的 RESEND_API_KEY 或 RECEIVER_EMAIL 未配置正确。")
        return

    feeds = read_feeds_file("feeds.txt")
    if not feeds:
        return

    email_body = fetch_and_build_html(feeds)

    if email_body:
        print(f"正在发送邮件至: {receiver_email}...")
        try:
            resend.Emails.send({
                "from": "Newsletter <onboarding@resend.dev>",
                "to": [receiver_email],
                "subject": f"今日资讯汇总 - {datetime.now().strftime('%Y-%m-%d')}",
                "html": email_body
            })
            print("✅ 邮件发送成功！")
        except Exception as e:
            print(f"❌ Resend API 报错: {e}")
    else:
        print("⚠️ 过去 24 小时内没有新内容更新，已跳过发送。")

if __name__ == "__main__":
    main()