#!/usr/bin/env python3
import sys
import os
import feedparser
import resend
from datetime import datetime, timezone, timedelta

# 配置 Resend 环境变量
resend.api_key = os.environ.get("RESEND_API_KEY")
receiver_email = os.environ.get("RECEIVER_EMAIL")

def read_feeds_file(filepath="feeds.txt"):
    """读取 feeds.txt 中的 RSS 链接"""
    feeds = []
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#'):
                    feeds.append(line)
    except FileNotFoundError:
        print(f"❌ Error: {filepath} not found!")
        return []
    return feeds

def fetch_and_build_html(feeds):
    """抓取资讯并构建具有高级样式的 HTML 模板"""
    now = datetime.now(timezone.utc)
    
    # 报纸头部样式
    html = """
    <div style="background-color: #f4f1ea; padding: 20px; font-family: 'Georgia', serif;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border: 1px solid #d3d3d3; padding: 30px; box-shadow: 2px 2px 10px rgba(0,0,0,0.1);">
            <div style="text-align: center; border-bottom: 4px double #333; padding-bottom: 10px; margin-bottom: 20px;">
                <h1 style="margin: 0; font-size: 32px; text-transform: uppercase; letter-spacing: 2px;">Daily Gazette</h1>
                <p style="margin: 5px 0; color: #666; font-style: italic;">{date}</p>
            </div>
    """.format(date=datetime.now().strftime('%A, %b %d, %Y'))

    total_entries = 0

    for url in feeds:
        try:
            print(f"Fetching: {url}")
            feed = feedparser.parse(url)
            source_title = feed.feed.get('title', 'Global News')
            
            # 栏目名称
            section_html = f'<h2 style="font-size: 20px; border-left: 5px solid #333; padding-left: 10px; margin-top: 30px; color: #1a1a1a;">{source_title}</h2>'
            
            has_content = False
            for entry in feed.entries:
                pub_parsed = getattr(entry, 'published_parsed', None) or getattr(entry, 'updated_parsed', None)
                if pub_parsed:
                    pub_date = datetime(*pub_parsed[:6], tzinfo=timezone.utc)
                    # 过滤 24 小时内资讯
                    if (now - pub_date) < timedelta(days=1):
                        summary = entry.get('summary', '')[:100] + '...' if 'summary' in entry else ''
                        section_html += f"""
                        <div style="margin-bottom: 15px; padding-bottom: 10px; border-bottom: 1px solid #eee;">
                            <a href="{entry.link}" style="text-decoration: none; color: #c0392b; font-weight: bold; font-size: 16px;">{entry.title}</a>
                            <p style="margin: 5px 0; font-size: 13px; color: #555; line-height: 1.5;">{summary}</p>
                        </div>
                        """
                        has_content = True
                        total_entries += 1
            
            if has_content:
                html += section_html
        except Exception as e:
            print(f"Error parsing {url}: {e}")

    # 页脚
    html += """
            <div style="margin-top: 40px; border-top: 1px solid #333; padding-top: 10px; text-align: center; font-size: 12px; color: #888;">
                <p>Generated by Rex's News Bot</p>
            </div>
        </div>
    </div>
    """
    return html if total_entries > 0 else None

def main():
    print("RSS Subscriber - Starting automation...")
    
    if not resend.api_key or not receiver_email:
        print("❌ Error: Missing environment variables (RESEND_API_KEY or RECEIVER_EMAIL).")
        return

    feeds = read_feeds_file("feeds.txt")
    if not feeds:
        return

    email_body = fetch_and_build_html(feeds)

    if email_body:
        print(f"Sending email to {receiver_email}...")
        try:
            resend.Emails.send({
                "from": "Newsletter <onboarding@resend.dev>",
                "to": [receiver_email],
                "subject": f"每日资讯汇总 - {datetime.now().strftime('%Y-%m-%d')}",
                "html": email_body
            })
            print("✅ Email sent successfully!")
        except Exception as e:
            print(f"❌ Resend API Error: {e}")
    else:
        print("⚠️ No updates found in the last 24 hours. No email sent.")

if __name__ == "__main__":
    main()